# overall/params.yaml

# Configuration for the overall ASI arrival simulation

# --- Timelines Configuration ---
timelines_config:
  # Specify which forecaster's AGI estimates to use from timelines/params.yaml
  # Or define a custom AGI arrival distribution here
  forecaster_to_use: "eli" # Options: "eli", "nikola", "brendan", or a path to a custom AGI dates file
  # Example for custom AGI:
  # agi_arrival_years_file: "path/to/agi_dates.csv" # CSV file with one column of AGI arrival years

  # Parameters from timelines/params.yaml (can be overridden if needed, but usually inherited)
  # n_sims: 5000 # Number of AGI arrival samples to generate if not using a file
  # t_0: 2025
  # dt_timelines: 1.0 # days, renamed to avoid clash with takeoff dt

# --- Takeoff Configuration ---
# Parameters adapted from takeoff/params.yaml
takeoff_config:
  # starting_time will be derived from the timelines simulation output

  # Time gaps between milestones in years (human-equivalent, before speedups)
  # Format: [p_zero, lower_bound_80_ci, upper_bound_80_ci]
  # p_zero: probability that the time gap is effectively zero (milestones occur simultaneously or very close)
  times:
    "SC to SAR": [0.15, 1.5, 10]    # Supervised Capability to Superhuman AI Routines
    "SAR to SIAR": [0.0, 2, 250]    # Superhuman AI Routines to Superhuman Intelligence Across Routines
    "SIAR to ASI": [0.0, 3, 500]    # Superhuman Intelligence Across Routines to Artificial Superintelligence
    # "ASI to WS": [0, 4, 1000] # Currently unused in original takeoff, can be added if model supports it

  # Speed multipliers at each milestone (v_milestone)
  # These represent how much faster AI progresses compared to human-equivalent effort
  # once a milestone is reached.
  speedups:
    SC: 5       # Speedup after achieving SC
    SAR: 25     # Speedup after achieving SAR
    SIAR: 250   # Speedup after achieving SIAR
    ASI: 2000   # Speedup after achieving ASI (relevant for modeling post-ASI dynamics if any)
    # WS: 10000 # World Settlement, unused

  # General simulation parameters for the takeoff part
  # n_sims: 5000 # Will be tied to the number of AGI samples from timelines
  dt_takeoff: 1.0 # days, renamed to avoid clash

# --- Overall Simulation Parameters ---
overall_simulation:
  n_sims: 5000 # Number of end-to-end simulations (AGI date -> ASI date)
  # Correlation for sampling in takeoff model (can be adjusted)
  takeoff_gap_correlation: 0.7


# --- Plotting Configuration ---
plotting_style:
  font:
    family: "monospace"
    sizes:
      axis_labels: 18
      title: 18
      main_title: 32
      ticks: 16
      legend: 16
      small: 14
  colors:
    background: "#FFFEF8"
    human:
      dark: "#484848"
    default: "#0077b6" # A nice blue for the overall forecast
    timelines_output: "#009688" # Teal for AGI distribution
    takeoff_duration: "#f4a261" # Orange for takeoff duration 